{if count($flights) > 0}
	{foreach $flights as $flight}
        <div class="flight">
		
		{foreach $flight->legs as $leg}
		<ul>
                    <li>Airline: {$leg->getAirlineDisplay()}</li>
	            <li>From: {$leg->getOrig()} {$leg->getDepart()->format('j. n. Y G:i')}</li>
	            <li>To: {$leg->getDest()} {$leg->getArrive()->format('j. n. Y G:i')}</li>
	            <li>Duration: {$leg->getDurationTime()}</li>
	            <li>Cabin: {$leg->getCabin()}</li>
	        </ul>
		{/foreach}
                <div>{$flight->price} {$flight->currency}</div>
                <div>For booking continue <a href="{link Trip:booking, 'id' => $trip->id, 'flightId' => $iterator->counter}">here</a>.</div>
        </div>
	{/foreach}
{else}
	<p>No flights available.</p>
{/if}