{if count($hotels) > 0}
	{foreach $hotels as $hotel}
            <div class="hotel">
                <div>{$hotel->getLodgingType()}</div>
                <div>Star rating: {$hotel->getStarRating()}</div>
                <ul>
		{foreach $hotel->getAmenities() as $amenity}
                    <li>{$amenity}</li>
		{/foreach}
                </ul>
                <a href="{$hotel->getLink()}">{$hotel->getTotalPrice()} {$hotel->getCurrency()} </a>
            </div>
	{/foreach}
{else}
	<p>No hotels available.</p>
{/if}
