{if count($hotels) > 0}
	{foreach $hotels as $hotel}
            <div class="hotel">
                <div>{$hotel->getLodgingType()}</div>
                <div>{$hotel->getStarRating()}</div>
                <ul>
		{foreach $hotel->getAmenities() as $amenity}
                    <li>{$amenity}</li>
		{/foreach}
                </ul>
                <div>Price per night: {$hotel->getPricePerNight()} {$hotel->getCurrency()}</div>
                <div>Total price: {$hotel->getTotalPrice()} {$hotel->getCurrency()} </div>
                <div>For booking continue <a href="{$hotel->getLink()}">here</a>.</div>
            </div>
	{/foreach}
{else}
	<p>No hotels available.</p>
{/if}
