CREATE TABLE trip (
	id SERIAL PRIMARY KEY,
	departure VARCHAR(256) NOT NULL,
	arrival VARCHAR(256) NOT NULL
) WITHOUT OIDS;

CREATE TABLE step (
	id SERIAL PRIMARY KEY,
	trip_id INTEGER NOT NULL REFERENCES trip(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	sequenceorder INTEGER NOT NULL DEFAULT 0,
	distance INTEGER NOT NULL,
	duration INTEGER NOT NULL,
	instructions TEXT NOT NULL
) WITHOUT OIDS;