<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of MockHotelMapper
 *
 * @author Studio
 */
class MockHotelMapper implements IHotelMapper
{

    //put your code here
    public function searchHotels($lat, $log, DateTime $startdate,
            DateTime $enddate, $rooms, $adults, $children)
    {
        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Hotwire>
                    <Errors/>
                    <MetaData>
                        <HotelMetaData>
                            <Amenities>
                                <Amenity>
                                    <Code>AS</Code>
                                    <Description>Property offers transportation to and from the airport. Shuttles may run during limited hours or require a reservation; an additional charge may apply.</Description>
                                    <Name>Airport Shuttle</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>BC</Code>
                                    <Description>Guests have access to business equipment and services; an additional charge may apply.</Description>
                                    <Name>Business Center</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>BH</Code>
                                    <Description>Property offers a distinctive, unique or eclectic atmosphere. Many boutique hotels are smaller, hip properties in an urban setting, or renovated hotels with historical flair.</Description>
                                    <Name>Boutique Hotel</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>CB</Code>
                                    <Description>Rates include continental or full breakfast.</Description>
                                    <Name>Complimentary Breakfast</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>FC</Code>
                                    <Description>Guests have access to exercise equipment; an additional charge may apply.</Description>
                                    <Name>Fitness Center</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>HS</Code>
                                    <Description>Guestrooms are equipped with high-speed Internet access; an extra charge may apply.</Description>
                                    <Name>High-speed Internet Access</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>LF</Code>
                                    <Description>Guests have access to a coin-operated washer and dryer.</Description>
                                    <Name>Laundry Facilities</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>PO</Code>
                                    <Description>Property offers at least one pool area; hours and dates of operation may be seasonal.</Description>
                                    <Name>Pool(s)</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>RE</Code>
                                    <Description>Property offers at least one restaurant on the premises; hours and days of operation may vary.</Description>
                                    <Name>Restaurant(s)</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>SF</Code>
                                    <Description>Guests have access to a spa facility or spa services; an extra charge typically applies.</Description>
                                    <Name>Spa Services</Name>
                                </Amenity>
                                <Amenity>
                                    <Code>TN</Code>
                                    <Description>Property is located within walking distance or a short drive of at least one tennis court; an extra charge typically applies.</Description>
                                    <Name>Tennis Nearby</Name>
                                </Amenity>
                            </Amenities>
                            <Neighborhoods>
                                <Neighborhood>
                                    <Centroid>50.094595,14.481233</Centroid>
                                    <City>Prague</City>
                                    <Country>CZ</Country>
                                    <Id>89839</Id>
                                    <Name>Prague East</Name>
                                    <Shape>
                                        <LatLong>50.09438,14.44366</LatLong>
                                        <LatLong>50.09408,14.44109</LatLong>
                                        <LatLong>50.09397,14.44021</LatLong>
                                        <LatLong>50.09342,14.4396</LatLong>
                                        <LatLong>50.09259,14.43933</LatLong>
                                        <LatLong>50.0847,14.43894</LatLong>
                                        <LatLong>50.08338,14.43933</LatLong>
                                        <LatLong>50.08249,14.44016</LatLong>
                                        <LatLong>50.08148,14.44221</LatLong>
                                        <LatLong>50.08118,14.45496</LatLong>
                                        <LatLong>50.08257,14.45932</LatLong>
                                        <LatLong>50.08518,14.46968</LatLong>
                                        <LatLong>50.08545,14.4731</LatLong>
                                        <LatLong>50.08554,14.47823</LatLong>
                                        <LatLong>50.08482,14.48201</LatLong>
                                        <LatLong>50.08365,14.48606</LatLong>
                                        <LatLong>50.083364,14.486597</LatLong>
                                        <LatLong>50.076028,14.498008</LatLong>
                                        <LatLong>50.075734,14.500656</LatLong>
                                        <LatLong>50.077205,14.503304</LatLong>
                                        <LatLong>50.079853,14.505364</LatLong>
                                        <LatLong>50.106631,14.510956</LatLong>
                                        <LatLong>50.115459,14.506542</LatLong>
                                        <LatLong>50.116047,14.504482</LatLong>
                                        <LatLong>50.116047,14.501833</LatLong>
                                        <LatLong>50.106957,14.479583</LatLong>
                                        <LatLong>50.104966,14.474708</LatLong>
                                        <LatLong>50.096914,14.455001</LatLong>
                                        <LatLong>50.09438,14.44366</LatLong>
                                    </Shape>
                                    <State>CZ</State>
                                </Neighborhood>
                                <Neighborhood>
                                    <Centroid>50.054956,14.460731</Centroid>
                                    <City>Prague</City>
                                    <Country>CZ</Country>
                                    <Id>89840</Id>
                                    <Name>Prague Southeast</Name>
                                    <Shape>
                                        <LatLong>50.079301,14.432836</LatLong>
                                        <LatLong>50.077658,14.431467</LatLong>
                                        <LatLong>50.077584,14.431406</LatLong>
                                        <LatLong>50.076378,14.430401</LatLong>
                                        <LatLong>50.075527,14.430296</LatLong>
                                        <LatLong>50.075388,14.43024</LatLong>
                                        <LatLong>50.075346,14.430004</LatLong>
                                        <LatLong>50.075341,14.429933</LatLong>
                                        <LatLong>50.075318,14.429614</LatLong>
                                        <LatLong>50.075291,14.429212</LatLong>
                                        <LatLong>50.075179,14.429198</LatLong>
                                        <LatLong>50.073567,14.429337</LatLong>
                                        <LatLong>50.071405,14.429489</LatLong>
                                        <LatLong>50.0703,14.42866</LatLong>
                                        <LatLong>50.06893,14.42755</LatLong>
                                        <LatLong>50.0675,14.42569</LatLong>
                                        <LatLong>50.06681,14.42135</LatLong>
                                        <LatLong>50.06591,14.42008</LatLong>
                                        <LatLong>50.06376,14.41928</LatLong>
                                        <LatLong>50.06011,14.41906</LatLong>
                                        <LatLong>50.057816,14.41821</LatLong>
                                        <LatLong>50.056729,14.418435</LatLong>
                                        <LatLong>50.044985,14.425162</LatLong>
                                        <LatLong>50.039649,14.429258</LatLong>
                                        <LatLong>50.032716,14.434578</LatLong>
                                        <LatLong>50.030939,14.43742</LatLong>
                                        <LatLong>50.030939,14.440617</LatLong>
                                        <LatLong>50.030939,14.444168</LatLong>
                                        <LatLong>50.035609,14.463668</LatLong>
                                        <LatLong>50.029174,14.48802</LatLong>
                                        <LatLong>50.029174,14.49207</LatLong>
                                        <LatLong>50.033629,14.504018</LatLong>
                                        <LatLong>50.035654,14.506043</LatLong>
                                        <LatLong>50.036869,14.506043</LatLong>
                                        <LatLong>50.038894,14.505436</LatLong>
                                        <LatLong>50.071619,14.485187</LatLong>
                                        <LatLong>50.080227,14.481642</LatLong>
                                        <LatLong>50.081342,14.480875</LatLong>
                                        <LatLong>50.08311,14.47616</LatLong>
                                        <LatLong>50.0832,14.47346</LatLong>
                                        <LatLong>50.08311,14.4695</LatLong>
                                        <LatLong>50.08176,14.46347</LatLong>
                                        <LatLong>50.07896,14.45306</LatLong>
                                        <LatLong>50.078914,14.450052</LatLong>
                                        <LatLong>50.081013,14.436896</LatLong>
                                        <LatLong>50.079151,14.433584</LatLong>
                                        <LatLong>50.07931,14.432846</LatLong>
                                        <LatLong>50.079301,14.432836</LatLong>
                                    </Shape>
                                    <State>CZ</State>
                                </Neighborhood>
                                <Neighborhood>
                                    <Centroid>50.05926,14.369175</Centroid>
                                    <City>Prague</City>
                                    <Country>CZ</Country>
                                    <Id>89841</Id>
                                    <Name>Prague Southwest</Name>
                                    <Shape>
                                        <LatLong>50.07027,14.3226</LatLong>
                                        <LatLong>50.06876,14.31599</LatLong>
                                        <LatLong>50.06456,14.31479</LatLong>
                                        <LatLong>50.06066,14.31749</LatLong>
                                        <LatLong>50.03664,14.38444</LatLong>
                                        <LatLong>50.03754,14.39344</LatLong>
                                        <LatLong>50.04328,14.40237</LatLong>
                                        <LatLong>50.06442,14.40442</LatLong>
                                        <LatLong>50.06619,14.40608</LatLong>
                                        <LatLong>50.06717,14.40834</LatLong>
                                        <LatLong>50.06834,14.41049</LatLong>
                                        <LatLong>50.07059,14.41108</LatLong>
                                        <LatLong>50.07255,14.41049</LatLong>
                                        <LatLong>50.07292,14.40972</LatLong>
                                        <LatLong>50.07299,14.40907</LatLong>
                                        <LatLong>50.07357,14.38894</LatLong>
                                        <LatLong>50.073467,14.386865</LatLong>
                                        <LatLong>50.073862,14.38545</LatLong>
                                        <LatLong>50.074422,14.384946</LatLong>
                                        <LatLong>50.075264,14.384833</LatLong>
                                        <LatLong>50.07947,14.384609</LatLong>
                                        <LatLong>50.080087,14.384272</LatLong>
                                        <LatLong>50.080199,14.383487</LatLong>
                                        <LatLong>50.080087,14.379113</LatLong>
                                        <LatLong>50.07975,14.378216</LatLong>
                                        <LatLong>50.079358,14.377094</LatLong>
                                        <LatLong>50.072308,14.36357</LatLong>
                                        <LatLong>50.07027,14.3226</LatLong>
                                    </Shape>
                                    <State>CZ</State>
                                </Neighborhood>
                                <Neighborhood>
                                    <Centroid>50.083123,14.411548</Centroid>
                                    <City>Prague</City>
                                    <Country>CZ</Country>
                                    <Id>89842</Id>
                                    <Name>Central Prague</Name>
                                    <Shape>
                                        <LatLong>50.075611,14.429559</LatLong>
                                        <LatLong>50.075612,14.429561</LatLong>
                                        <LatLong>50.075638,14.429809</LatLong>
                                        <LatLong>50.075763,14.429907</LatLong>
                                        <LatLong>50.078051,14.430879</LatLong>
                                        <LatLong>50.07934,14.43188</LatLong>
                                        <LatLong>50.08404,14.4353</LatLong>
                                        <LatLong>50.08608,14.43787</LatLong>
                                        <LatLong>50.08845,14.43836</LatLong>
                                        <LatLong>50.0921,14.43867</LatLong>
                                        <LatLong>50.09295,14.43879</LatLong>
                                        <LatLong>50.09344,14.43872</LatLong>
                                        <LatLong>50.09356,14.4383</LatLong>
                                        <LatLong>50.09325,14.42925</LatLong>
                                        <LatLong>50.09293,14.42706</LatLong>
                                        <LatLong>50.09277,14.42012</LatLong>
                                        <LatLong>50.09217,14.41578</LatLong>
                                        <LatLong>50.09169,14.41298</LatLong>
                                        <LatLong>50.09265,14.41134</LatLong>
                                        <LatLong>50.0941,14.41067</LatLong>
                                        <LatLong>50.09506,14.40961</LatLong>
                                        <LatLong>50.09554,14.40816</LatLong>
                                        <LatLong>50.09255,14.39264</LatLong>
                                        <LatLong>50.09169,14.38839</LatLong>
                                        <LatLong>50.09043,14.38695</LatLong>
                                        <LatLong>50.08744,14.38608</LatLong>
                                        <LatLong>50.08417,14.38579</LatLong>
                                        <LatLong>50.0824,14.386393</LatLong>
                                        <LatLong>50.075427,14.386667</LatLong>
                                        <LatLong>50.07501,14.386759</LatLong>
                                        <LatLong>50.074732,14.38713</LatLong>
                                        <LatLong>50.073667,14.399356</LatLong>
                                        <LatLong>50.073537,14.413081</LatLong>
                                        <LatLong>50.07346,14.41337</LatLong>
                                        <LatLong>50.07086,14.41346</LatLong>
                                        <LatLong>50.06921,14.41422</LatLong>
                                        <LatLong>50.06897,14.4151</LatLong>
                                        <LatLong>50.06897,14.41552</LatLong>
                                        <LatLong>50.06897,14.42154</LatLong>
                                        <LatLong>50.06911,14.42238</LatLong>
                                        <LatLong>50.0702,14.42585</LatLong>
                                        <LatLong>50.07028,14.42745</LatLong>
                                        <LatLong>50.07067,14.4286</LatLong>
                                        <LatLong>50.07189,14.429261</LatLong>
                                        <LatLong>50.075416,14.429003</LatLong>
                                        <LatLong>50.075554,14.429031</LatLong>
                                        <LatLong>50.075597,14.42917</LatLong>
                                        <LatLong>50.075611,14.429559</LatLong>
                                    </Shape>
                                    <State>CZ</State>
                                </Neighborhood>
                                <Neighborhood>
                                    <Centroid>50.097777,14.349003</Centroid>
                                    <City>Prague</City>
                                    <Country>CZ</Country>
                                    <Id>89843</Id>
                                    <Name>Prague Northwest</Name>
                                    <Shape>
                                        <LatLong>50.10301,14.2894</LatLong>
                                        <LatLong>50.10043,14.28617</LatLong>
                                        <LatLong>50.09655,14.28649</LatLong>
                                        <LatLong>50.09234,14.29037</LatLong>
                                        <LatLong>50.08911,14.29684</LatLong>
                                        <LatLong>50.07908,14.34017</LatLong>
                                        <LatLong>50.0802,14.37461</LatLong>
                                        <LatLong>50.08131,14.37971</LatLong>
                                        <LatLong>50.08275,14.38098</LatLong>
                                        <LatLong>50.08649,14.38265</LatLong>
                                        <LatLong>50.08928,14.38409</LatLong>
                                        <LatLong>50.09238,14.38775</LatLong>
                                        <LatLong>50.09381,14.39062</LatLong>
                                        <LatLong>50.09421,14.39324</LatLong>
                                        <LatLong>50.09429,14.39587</LatLong>
                                        <LatLong>50.09509,14.39962</LatLong>
                                        <LatLong>50.09762,14.40467</LatLong>
                                        <LatLong>50.09984,14.4161</LatLong>
                                        <LatLong>50.10108,14.417</LatLong>
                                        <LatLong>50.10254,14.417</LatLong>
                                        <LatLong>50.10457,14.4161</LatLong>
                                        <LatLong>50.10784,14.41292</LatLong>
                                        <LatLong>50.10831,14.41276</LatLong>
                                        <LatLong>50.10942,14.41068</LatLong>
                                        <LatLong>50.11045,14.40098</LatLong>
                                        <LatLong>50.110763,14.398333</LatLong>
                                        <LatLong>50.111646,14.396449</LatLong>
                                        <LatLong>50.112797,14.36468</LatLong>
                                        <LatLong>50.111186,14.314955</LatLong>
                                        <LatLong>50.110955,14.302984</LatLong>
                                        <LatLong>50.103124,14.290006</LatLong>
                                        <LatLong>50.10301,14.2894</LatLong>
                                    </Shape>
                                    <State>CZ</State>
                                </Neighborhood>
                            </Neighborhoods>
                        </HotelMetaData>
                    </MetaData>
                    <Result>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQyNQ--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQyNQ--</ResultId>
                            <HWRefNumber>5172017630</HWRefNumber>
                            <SubTotal>480.00</SubTotal>
                            <TaxesAndFees>68.60</TaxesAndFees>
                            <TotalPrice>548.60</TotalPrice>
                            <AmenityCodes>
                                <Code>BH</Code>
                                <Code>RE</Code>
                                <Code>BC</Code>
                                <Code>HS</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89842</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>96.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>5.0</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQwOA--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQwOA--</ResultId>
                            <HWRefNumber>6993547054</HWRefNumber>
                            <SubTotal>230.00</SubTotal>
                            <TaxesAndFees>26.66</TaxesAndFees>
                            <TotalPrice>256.66</TotalPrice>
                            <AmenityCodes>
                                <Code>AS</Code>
                                <Code>CB</Code>
                                <Code>RE</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89842</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>46.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>2.5</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQyMA--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQyMA--</ResultId>
                            <HWRefNumber>5897898836</HWRefNumber>
                            <SubTotal>210.00</SubTotal>
                            <TaxesAndFees>12.09</TaxesAndFees>
                            <TotalPrice>222.09</TotalPrice>
                            <AmenityCodes>
                                <Code>CB</Code>
                                <Code>FC</Code>
                                <Code>PO</Code>
                                <Code>RE</Code>
                                <Code>BC</Code>
                                <Code>HS</Code>
                                <Code>TN</Code>
                                <Code>SF</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89840</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>42.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>4.0</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQyNg--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQyNg--</ResultId>
                            <HWRefNumber>6954538767</HWRefNumber>
                            <SubTotal>175.00</SubTotal>
                            <TaxesAndFees>11.64</TaxesAndFees>
                            <TotalPrice>186.64</TotalPrice>
                            <AmenityCodes>
                                <Code>RE</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89841</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>35.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>3.5</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQwNQ--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQwNQ--</ResultId>
                            <HWRefNumber>5467690536</HWRefNumber>
                            <SubTotal>150.00</SubTotal>
                            <TaxesAndFees>11.56</TaxesAndFees>
                            <TotalPrice>161.56</TotalPrice>
                            <AmenityCodes/>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89839</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>30.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>3.0</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQwOQ--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQwOQ--</ResultId>
                            <HWRefNumber>6692141177</HWRefNumber>
                            <SubTotal>315.00</SubTotal>
                            <TaxesAndFees>13.42</TaxesAndFees>
                            <TotalPrice>328.42</TotalPrice>
                            <AmenityCodes/>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89839</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>63.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>3.5</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQxMg--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQxMg--</ResultId>
                            <HWRefNumber>6960154318</HWRefNumber>
                            <SubTotal>630.00</SubTotal>
                            <TaxesAndFees>43.82</TaxesAndFees>
                            <TotalPrice>673.82</TotalPrice>
                            <AmenityCodes>
                                <Code>FC</Code>
                                <Code>PO</Code>
                                <Code>RE</Code>
                                <Code>LF</Code>
                                <Code>HS</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89843</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>126.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>4.5</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQxOQ--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQxOQ--</ResultId>
                            <HWRefNumber>5206332938</HWRefNumber>
                            <SubTotal>395.00</SubTotal>
                            <TaxesAndFees>14.33</TaxesAndFees>
                            <TotalPrice>409.33</TotalPrice>
                            <AmenityCodes>
                                <Code>RE</Code>
                                <Code>BC</Code>
                                <Code>HS</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89843</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>79.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>3.5</StarRating>
                        </HotelResult>
                        <HotelResult>
                            <CurrencyCode>USD</CurrencyCode>
                            <DeepLink>http://www.hotwire.com/hotel/deeplink-details.jsp?resultId=NTY0MDA0NzIwMjo5MTI5NzI5NjQxMw--&amp;sid=B001&amp;bid=B001&amp;inputId=api-results&amp;actionType=303</DeepLink>
                            <ResultId>NTY0MDA0NzIwMjo5MTI5NzI5NjQxMw--</ResultId>
                            <HWRefNumber>6744357759</HWRefNumber>
                            <SubTotal>245.00</SubTotal>
                            <TaxesAndFees>33.42</TaxesAndFees>
                            <TotalPrice>278.42</TotalPrice>
                            <AmenityCodes>
                                <Code>CB</Code>
                                <Code>RE</Code>
                            </AmenityCodes>
                            <CheckInDate>01/10/2011</CheckInDate>
                            <CheckOutDate>01/15/2011</CheckOutDate>
                            <NeighborhoodId>89843</NeighborhoodId>
                            <LodgingTypeCode>H</LodgingTypeCode>
                            <Nights>5</Nights>
                            <PaidAmenities/>
                            <AveragePricePerNight>49.00</AveragePricePerNight>
                            <Rooms>1</Rooms>
                            <SpecialTaxItems/>
                            <StarRating>2.0</StarRating>
                        </HotelResult>
                    </Result>
                    <StatusCode>0</StatusCode>
                    <StatusDesc>success</StatusDesc>
                </Hotwire>';
    }

}
?>
