{block #htmlTag}<html xmlns:og="http://opengraphprotocol.org/schema/">{/block}
{block #meta}
	<meta property="og:title" content="{block #title}Trip from {$trip->departure} to {$trip->arrival}{/block}">
	<meta property="og:url" content="{link //this}">
	<meta property="og:site_name" content="Travelbot">
{/block}

{block #header}
	<strong class="departure">From</strong>
	<span class="trip departure">{$trip->departure}</span>
	
	<strong class="arrival">To</strong>
	<span class="trip arrival">{$trip->arrival}</span>
	
	<span id="tripid" style="display: none;">{$trip->id}</span>
{/block}

{block #js}
	<script type="text/javascript">
		var isTripPage = true;
	</script>
{/block}

{block #content}
	
	<p class="nav"><a href="{link Homepage:}">← Plan new trip</a> | <a href="{link this}">permalink</a> | <a href="{link summary}">summary</a></p>
	
	<iframe src="http://www.facebook.com/plugins/like.php?locale=en_GB&amp;href={link //this}&amp;layout=button_count&amp;action=like&amp;font=trebuchet+ms&amp;colorscheme=light&amp;" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width: 90px; height: 30px;" allowTransparency="true"></iframe>
	
	<p class="clear">The trip will take <strong>{$trip->duration |duration}</strong> to complete and its distance is <strong>{$trip->distance |distance}</strong>.</p>
	
	<div>
		<div id="article"></div>
	</div>
	
	<div>
		<ol id="directions">
			{foreach $trip->steps as $step}
                            <li class="step" data-polyline="{$step->polyline}">{!$step->instructions} ({$step->distance |distance}).</li>
			{/foreach}
		</ol>
	</div>
	
	<div>
		<div id="pois"></div>
	</div>
	
	<div>
		<div id="events"></div>
	</div>
	
	<div>
		<div id="flights"></div>
	</div>

        <div>
		<div id="hotels"></div>
	</div>
