{block #content}

<p><a href="{link default}">Saved trips</a> &gt; <strong>Trip {$trip->id}</strong></p>

<table>
    <tr class="required">
        <th>From</th>
        <td id="trip-from">{$trip->departure}</td>
    </tr>

    <tr class="required">
        <th>To</th>
        <td id="trip-to">{$trip->arrival}</td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="article">{!$article->text}</div>
        </td>
    </tr>
    <tr>
        <td id="directions-text" colspan="2">
            <p>The trip will take <strong>{$trip->duration |duration}</strong> to complete and its distance is <strong>{$trip->distance |distance}</strong>.</p>
            <ol>
				{foreach $trip->steps as $step}
                <li>{!$step->instructions} ({$step->distance |distance}).</li>
				{/foreach}
            </ol>
        </td>
    </tr>
</table>
<div id="map_canvas"></div>
<div id="panel"></div>

<table border="2" id="flights">
    {foreach $flights as $flight}
    <tr>
    <td>
        <a href="http://kayak.com{$flight->getBook()}">{$flight->getPrice()} {$flight->getCurrency()}</a>
    </td>
        
        {foreach $flight->getLegs() as $leg}
        <td>
            <p>Airline: <strong>{$leg->getAirlineDisplay()}</strong></p>
            <p>From:  <strong>{$leg->getOrig()} {$leg->getDepart()} </strong></p>
            <p>To:  <strong>{$leg->getDest()} {$leg->getArrive()} </strong></p>
            <p>Duration: {$leg->getDurationTime()}</p>
            <p>Cabin: {$leg->getCabin()}</p>

            {foreach $leg->getSegments() as $segment}

            {/foreach}
        </td>
        {/foreach}
        
    </tr>
    {/foreach}
</table>

<h2>Events</h2>

{if count($events) > 0}
	{foreach $events as $event}
		<h3><a href="{$event->url}">{$event->title}</a> {$event->date->format('j. n. Y')}</h3>
		<div class="small">
			<p><strong>Where:</strong> <a href="{$event->venue->url}">{$event->venue->name}</a></p>
			{!$event->description}
		</div>
	{/foreach}
{else}
	<p>No events available.</p>
{/if}

