<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Nette Framework web application skeleton">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>Project Travelbot</title>

	<link rel="stylesheet" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">
</head>

<body>
	<div id="header">
		<h1><a href="{link Homepage:}">Travelbot</a></h1>
		<span>
			{ifCurrent Homepage:}
				<strong>Find directions</strong> -
			{else}
				<a href="{link Homepage:}">Find directions</a> -
			{/if} 
			
			{* {ifCurrent Trip:}
				<strong>Saved trips</strong> -
			{else}
				<a href="{link Trip:}">Saved trips</a> -
			{/if}  *}
			
			{ifCurrent About:}
				<strong>About</strong>
			{else}
				<a href="{link About:}">About</a>
			{/if}
		</span>
	</div>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	<div id="content">
		{include #content}
	</div>
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	<script type="text/javascript" src="http://www.google.com/jsapi?key=ABQIAAAAlg1WOiaaW_k8WYoVR1eO-RRrPYXs5Xp6xYkOfz_-imUsX-2tzRQNF8z1aFACCykMNbEvbuRV1eJXaw"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.geolocator.js"></script>
	<script type="text/javascript" src="{$basePath}/js/netteForms.js"></script>
	<script type="text/javascript" src="{$basePath}/js/travelbot.js"></script>
</body>
</html>
