<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Nette Framework web application skeleton">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>{block #title}{/block} | Travelbot</title>

	<link rel="stylesheet" href="{$basePath}/css/reset.css" type="text/css">
	<link rel="stylesheet" href="{$basePath}/css/simple.css" type="text/css" media="screen,print">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">
</head>

<body>
	<div id="content" class="inner">
		{include #content}
	</div>
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	<script type="text/javascript" src="http://www.google.com/jsapi?key={$mapsKey}"></script>
        <link href="http://code.google.com/apis/maps/documentation/javascript/examples/standard.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.geolocator.js"></script>
	<script type="text/javascript" src="{$basePath}/js/netteForms.js"></script>
	<script type="text/javascript" src="{$basePath}/js/netteAjaxForms.js"></script>
	<script type="text/javascript" src="{$basePath}/js/travelbot.js"></script>
</body>
</html>
